// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fegvbiomgoodcswveyqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZ3ZiaW9tZ29vZGNzd3ZleXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NTU2OTQsImV4cCI6MjA3NzAzMTY5NH0.7HECRtZ9BUqMeQMBowhaEPEDWGr-zd4JSh4MrqM_OCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});